version: '3'

services:
  hello-service:
    container_name: hello-service
    build: hello-service
    ports:
    - 8081:8081

  hi-service:
    container_name: hi-service
    build: hi-service
    ports:
    - 8082:8082

  gateway-service:
    container_name: gateway-service
    build: nginx
    ports:
    - 80:80
    restart: always
    links:
      - hi-service
      - hello-service